apiVersion: skaffold/v2beta15
kind: Config
metadata:
  name: server
build:
  artifacts:
  - image: dockeridohyeah/apps-auth
    docker:
      dockerfile: Dockerfile.auth
deploy:
  kubectl:
    manifests:
    - infra/k8s/auth-depl.yaml
    - infra/k8s/auth-mongo-depl.yaml
