apiVersion: skaffold/v2beta15
kind: Config
metadata:
  name: nest
build:
  artifacts:
  - image: dockeridohyeah/nest-auth
    docker:
      dockerfile: Dockerfile.auth
  - image: dockeridohyeah/nest-charege
    docker:
      dockerfile: Dockerfile.charge
  - image: dockeridohyeah/nest-tickets
    docker:
      dockerfile: Dockerfile.tickets
deploy:
  kubectl:
    manifests:
    - infra/k8s/auth-depl.yaml
    - infra/k8s/auth-mongo-depl.yaml
    - infra/k8s/auth-srv.yaml
    - infra/k8s/charge-depl.yaml
    - infra/k8s/charge-mongo-depl.yaml
    - infra/k8s/nats-depl.yaml
    - infra/k8s/tickets-depl.yaml
    - infra/k8s/tickets-mongo-depl.yaml
    - infra/k8s/tickets-srv.yaml
