apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: dockeridohyeah/nest-auth:latest
          env:
            - name: NODE_ENV
              value: development
            - name: access
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: access
            - name: accessExpiresIn
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: accessExpiresIn
            - name: token
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: token
            - name: tokenExpiresIn
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: tokenExpiresIn
                
                
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - port: 3001
      targetPort: 3001
