apiVersion: apps/v1
kind: Deployment
metadata:
  name: charge-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: charge-mongo
  template:
    metadata:
      labels:
        app: charge-mongo
    spec:
      containers:
        - name: charge-mongo
          image: mongo

---
apiVersion: v1
kind: Service
metadata:
  name: charge-mongo-srv
spec:
  selector:
    app: charge-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017