apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  selector:
    matchLabels:
      app: tickets-depl
  template:
    metadata:
      labels:
        app: tickets-depl
    spec:
      containers:
        - name: tickets
          image: dockeridohyeah/apps-tickets:latest
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'

---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - port: 3004
      targetPort: 3004
